services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mcplamen\Monthlyschedule\:
    resource: '../Classes/*'

  Mcplamen\Monthlyschedule\Controller\:
    resource: '../Classes/Controller'
    tags: ['backend.controller']
    
  Mcplamen\Monthlyschedule\ViewHelpers\WeekdayDeViewHelper:
    tags: ['fluid.viewhelper']
